import { Site, Theme } from './types';

export const THEMES: Theme[] = [
  {
    name: 'Cyberpunk',
    bgMode: 'grid',
    vars: {
      '--bg-color': '#050505',
      '--text-main': '#00f3ff',
      '--text-sub': 'rgba(0, 243, 255, 0.7)',
      '--glass-bg': 'rgba(0, 0, 0, 0.1)', 
      '--glass-surface': 'rgba(0, 243, 255, 0.03)', 
      '--glass-border': 'rgba(0, 243, 255, 0.3)', 
      '--card-shadow': '0 0 10px rgba(0, 243, 255, 0.05), inset 0 0 5px rgba(0, 243, 255, 0.02)', 
      '--card-shadow-hover': '0 0 25px rgba(0, 243, 255, 0.4), inset 0 0 10px rgba(0, 243, 255, 0.1)',
      '--card-hover': 'rgba(0, 243, 255, 0.1)',
      '--sidebar-bg': 'rgba(0, 0, 0, 0.4)',
      '--accent': '#ff0055',
      '--orb1': '#ff0055',
      '--orb2': '#00f3ff',
      '--orb3': '#ffee00',
      '--panel-blur': '0px',
      '--card-blur': '2px',
    } as React.CSSProperties
  },
  {
    name: 'iOS',
    bgMode: 'blobs',
    vars: {
      '--bg-color': '#f2f2f7',
      '--text-main': '#000000',
      '--text-sub': '#8e8e93',
      '--glass-bg': 'rgba(255, 255, 255, 0.65)',
      '--glass-surface': 'rgba(255, 255, 255, 0.5)',
      '--glass-border': 'rgba(255, 255, 255, 0.4)',
      '--card-shadow': '0 2px 10px rgba(0,0,0,0.05)',
      '--card-shadow-hover': '0 5px 20px rgba(0,0,0,0.1)',
      '--card-hover': 'rgba(255, 255, 255, 0.8)',
      '--sidebar-bg': 'rgba(255, 255, 255, 0.75)',
      '--accent': '#007aff',
      '--orb1': '#007aff',
      '--orb2': '#5ac8fa',
      '--orb3': '#5856d6',
      '--panel-blur': '50px',
      '--card-blur': '20px',
    } as React.CSSProperties
  },
  {
    name: 'Ocean',
    bgMode: 'waves',
    vars: {
      '--bg-color': '#001e36',
      '--text-main': '#e0f7fa',
      '--text-sub': '#80deea',
      '--glass-bg': 'rgba(0, 15, 30, 0.2)',
      '--glass-surface': 'rgba(0, 229, 255, 0.05)',
      '--glass-border': 'rgba(128, 222, 234, 0.15)',
      '--card-shadow': '0 4px 15px rgba(0, 0, 0, 0.2)',
      '--card-shadow-hover': '0 0 15px rgba(0, 229, 255, 0.3)',
      '--card-hover': 'rgba(0, 229, 255, 0.1)',
      '--sidebar-bg': 'rgba(0, 15, 30, 0.4)',
      '--accent': '#00e5ff',
      '--orb1': '#00e5ff',
      '--orb2': '#006064',
      '--orb3': '#18ffff',
      '--panel-blur': '5px',
      '--card-blur': '5px',
    } as React.CSSProperties
  },
  {
    name: 'Stars',
    bgMode: 'stars',
    vars: {
      '--bg-color': '#000000',
      '--text-main': '#ffffff',
      '--text-sub': 'rgba(255, 255, 255, 0.6)',
      '--glass-bg': 'rgba(0, 0, 0, 0.1)',
      '--glass-surface': 'rgba(255, 255, 255, 0.03)',
      '--glass-border': 'rgba(255, 255, 255, 0.08)',
      '--card-shadow': 'none',
      '--card-shadow-hover': '0 0 15px rgba(255, 255, 255, 0.15)',
      '--card-hover': 'rgba(255, 255, 255, 0.08)',
      '--sidebar-bg': 'rgba(0, 0, 0, 0.4)',
      '--accent': '#a855f7',
      '--orb1': '#ffffff',
      '--orb2': '#ffffff',
      '--orb3': '#ffffff',
      '--panel-blur': '0px',
      '--card-blur': '0px',
    } as React.CSSProperties
  },
  {
    name: 'Matrix',
    bgMode: 'matrix',
    vars: {
      '--bg-color': '#000000',
      '--text-main': '#00ff41',
      '--text-sub': '#008f11',
      '--glass-bg': 'rgba(0, 10, 0, 0.2)',
      '--glass-surface': 'rgba(0, 255, 65, 0.03)',
      '--glass-border': 'rgba(0, 255, 65, 0.2)',
      '--card-shadow': '0 0 5px rgba(0, 255, 65, 0.05)',
      '--card-shadow-hover': '0 0 15px rgba(0, 255, 65, 0.3)',
      '--card-hover': 'rgba(0, 255, 65, 0.1)',
      '--sidebar-bg': 'rgba(0, 10, 0, 0.5)',
      '--accent': '#00ff41',
      '--orb1': '#003b00',
      '--orb2': '#008f11',
      '--orb3': '#00ff41',
      '--panel-blur': '0px',
      '--card-blur': '2px',
    } as React.CSSProperties
  },
  {
    name: 'Neural',
    bgMode: 'neural',
    vars: {
      '--bg-color': '#0b0f19',
      '--text-main': '#e2e8f0',
      '--text-sub': '#94a3b8',
      '--glass-bg': 'rgba(15, 23, 42, 0.2)',
      '--glass-surface': 'rgba(56, 189, 248, 0.03)',
      '--glass-border': 'rgba(148, 163, 184, 0.1)',
      '--card-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      '--card-shadow-hover': '0 10px 15px -3px rgba(0, 0, 0, 0.3)',
      '--card-hover': 'rgba(56, 189, 248, 0.08)',
      '--sidebar-bg': 'rgba(15, 23, 42, 0.4)',
      '--accent': '#38bdf8',
      '--orb1': '#38bdf8',
      '--orb2': '#818cf8',
      '--orb3': '#c084fc',
      '--panel-blur': '3px',
      '--card-blur': '3px',
    } as React.CSSProperties
  },
  {
    name: 'Sunset',
    bgMode: 'sunset',
    vars: {
      '--bg-color': '#2a0a2e',
      '--text-main': '#ffd1d1',
      '--text-sub': '#ff9e9e',
      '--glass-bg': 'rgba(42, 10, 46, 0.2)',
      '--glass-surface': 'rgba(255, 100, 100, 0.05)',
      '--glass-border': 'rgba(255, 200, 100, 0.2)',
      '--card-shadow': '0 4px 15px rgba(0,0,0,0.1)',
      '--card-shadow-hover': '0 0 20px rgba(255, 160, 0, 0.2)',
      '--card-hover': 'rgba(255, 200, 0, 0.05)',
      '--sidebar-bg': 'rgba(50, 10, 50, 0.4)',
      '--accent': '#fbbf24',
      '--orb1': '#f59e0b',
      '--orb2': '#ef4444',
      '--orb3': '#ec4899',
      '--panel-blur': '5px',
      '--card-blur': '5px',
    } as React.CSSProperties
  },
  {
    name: 'Ice',
    bgMode: 'snow',
    vars: {
      '--bg-color': '#0f172a',
      '--text-main': '#f1f5f9',
      '--text-sub': '#94a3b8',
      '--glass-bg': 'rgba(15, 23, 42, 0.2)',
      '--glass-surface': 'rgba(56, 189, 248, 0.05)',
      '--glass-border': 'rgba(56, 189, 248, 0.3)',
      '--card-shadow': '0 0 10px rgba(56,189,248,0.05)',
      '--card-shadow-hover': '0 0 20px rgba(56, 189, 248, 0.3)',
      '--card-hover': 'rgba(56, 189, 248, 0.1)',
      '--sidebar-bg': 'rgba(15, 23, 42, 0.4)',
      '--accent': '#38bdf8',
      '--orb1': '#e0f2fe',
      '--orb2': '#7dd3fc',
      '--orb3': '#0ea5e9',
      '--panel-blur': '3px',
      '--card-blur': '3px',
    } as React.CSSProperties
  },
  {
    name: 'Limbo',
    bgMode: 'fire',
    vars: {
      '--bg-color': '#0f0014',
      '--text-main': '#e9d5ff',
      '--text-sub': '#c084fc',
      '--glass-bg': 'rgba(20, 0, 30, 0.2)',
      '--glass-surface': 'rgba(168, 85, 247, 0.05)',
      '--glass-border': 'rgba(192, 132, 252, 0.2)',
      '--card-shadow': '0 0 10px rgba(168, 85, 247, 0.05)',
      '--card-shadow-hover': '0 0 20px rgba(216, 180, 254, 0.3)',
      '--card-hover': 'rgba(168, 85, 247, 0.08)',
      '--sidebar-bg': 'rgba(20, 0, 30, 0.5)',
      '--accent': '#d8b4fe',
      '--orb1': '#7e22ce',
      '--orb2': '#9333ea',
      '--orb3': '#a855f7',
      '--panel-blur': '2px',
      '--card-blur': '2px',
    } as React.CSSProperties
  },
  {
    name: 'Sakura',
    bgMode: 'sakura',
    vars: {
      '--bg-color': '#1a1012',
      '--text-main': '#fce7f3',
      '--text-sub': '#f472b6',
      '--glass-bg': 'rgba(31, 16, 20, 0.1)',
      '--glass-surface': 'rgba(255, 255, 255, 0.03)',
      '--glass-border': 'rgba(244, 114, 182, 0.15)',
      '--card-shadow': 'none',
      '--card-shadow-hover': '0 0 15px rgba(244, 114, 182, 0.2)',
      '--card-hover': 'rgba(244, 114, 182, 0.05)',
      '--sidebar-bg': 'rgba(31, 16, 20, 0.3)',
      '--accent': '#f472b6',
      '--orb1': '#f472b6',
      '--orb2': '#db2777',
      '--orb3': '#be185d',
      '--panel-blur': '0px',
      '--card-blur': '0px',
    } as React.CSSProperties
  },
  {
    name: 'Aurora',
    bgMode: 'particles',
    vars: {
      '--bg-color': '#050714',
      '--text-main': '#ffffff',
      '--text-sub': 'rgba(255, 255, 255, 0.65)',
      '--glass-bg': 'rgba(30, 30, 35, 0.3)',
      '--glass-surface': 'rgba(255, 255, 255, 0.1)',
      '--glass-border': 'rgba(255, 255, 255, 0.1)',
      '--card-shadow': '0 4px 6px rgba(0,0,0,0.1)',
      '--card-shadow-hover': '0 10px 15px rgba(0,0,0,0.2)',
      '--card-hover': 'rgba(255, 255, 255, 0.1)',
      '--sidebar-bg': 'rgba(20, 20, 25, 0.6)',
      '--accent': '#00d2ff',
      '--orb1': '#00ff9d',
      '--orb2': '#bd00ff',
      '--orb3': '#00b8ff',
      '--panel-blur': '30px',
      '--card-blur': '12px',
    } as React.CSSProperties
  }
];

export const INITIAL_SITES: Site[] = [
    // SHEIN
    {n:"SHEIN 美国", u:"https://us.shein.com", t:["北美","总部"], c:"shein"},
    {n:"SHEIN 加拿大", u:"https://ca.shein.com", t:["北美","加元"], c:"shein"},
    {n:"SHEIN 墨西哥", u:"https://www.shein.com.mx", t:["拉美","西语"], c:"shein"},
    {n:"SHEIN 巴西", u:"https://br.shein.com", t:["南美","葡语"], c:"shein"},
    {n:"SHEIN 阿根廷", u:"https://m.shein.com/arg/", t:["南美"], c:"shein"},
    {n:"SHEIN 英国", u:"https://www.shein.co.uk", t:["欧洲","英镑"], c:"shein"},
    {n:"SHEIN 西班牙", u:"https://es.shein.com", t:["欧洲","西语"], c:"shein"},
    {n:"SHEIN 法国", u:"https://fr.shein.com", t:["欧洲","法语"], c:"shein"},
    {n:"SHEIN 德国", u:"https://de.shein.com", t:["欧洲","德语"], c:"shein"},
    {n:"SHEIN 意大利", u:"https://it.shein.com", t:["欧洲","意语"], c:"shein"},
    {n:"SHEIN 荷兰", u:"https://nl.shein.com", t:["欧洲","荷语"], c:"shein"},
    {n:"SHEIN 葡萄牙", u:"https://pt.shein.com", t:["欧洲","葡语"], c:"shein"},
    {n:"SHEIN 瑞典", u:"https://se.shein.com", t:["北欧"], c:"shein"},
    {n:"SHEIN 波兰", u:"https://pl.shein.com", t:["东欧"], c:"shein"},
    {n:"SHEIN 丹麦", u:"https://dk.shein.com", t:["北欧"], c:"shein"},
    {n:"SHEIN 罗马尼亚", u:"https://ro.shein.com", t:["东欧"], c:"shein"},
    {n:"SHEIN 瑞士", u:"https://ch.shein.com", t:["中欧"], c:"shein"},
    {n:"SHEIN 奥地利", u:"https://m.shein.com/at/", t:["中欧","德语"], c:"shein"},
    {n:"SHEIN 日本", u:"https://jp.shein.com", t:["亚太","日语"], c:"shein"},
    {n:"SHEIN 韩国", u:"https://kr.shein.com", t:["亚太","韩语"], c:"shein"},
    {n:"SHEIN 新加坡", u:"https://sg.shein.com", t:["东南亚"], c:"shein"},
    {n:"SHEIN 马来西亚", u:"https://my.shein.com", t:["东南亚"], c:"shein"},
    {n:"SHEIN 泰国", u:"https://th.shein.com", t:["东南亚","泰语"], c:"shein"},
    {n:"SHEIN 菲律宾", u:"https://ph.shein.com", t:["东南亚"], c:"shein"},
    {n:"SHEIN 印尼", u:"https://id.shein.com", t:["东南亚"], c:"shein"},
    {n:"SHEIN 越南", u:"https://www.shein.com.vn", t:["东南亚"], c:"shein"},
    {n:"SHEIN 香港", u:"https://www.shein.com.hk", t:["亚太","繁体"], c:"shein"},
    {n:"SHEIN 澳洲", u:"https://au.shein.com", t:["澳洲","澳元"], c:"shein"},
    {n:"SHEIN 阿语区", u:"https://ar.shein.com", t:["中东","沙特"], c:"shein"},
    {n:"SHEIN 以色列", u:"https://il.shein.com", t:["中东"], c:"shein"},
    {n:"SHEIN 摩洛哥", u:"https://ma.shein.com", t:["北非"], c:"shein"},
    {n:"SHEIN 南非", u:"https://za.shein.com", t:["非洲"], c:"shein"},
    {n:"SHEIN EUR", u:"https://eur.shein.com", t:["欧盟","EUR"], c:"shein"},
    {n:"SHEIN EUQS", u:"https://euqs.shein.com", t:["欧盟"], c:"shein"},
    {n:"SHEIN ROE", u:"https://roe.shein.com", t:["全球"], c:"shein"},

    // Young
    {n:"Easy Clothes", u:"https://www.easy-clothes.us", t:["美国","休闲"], c:"young"},
    {n:"Sungtin", u:"https://sungtin.com", t:["韩系","基础"], c:"young"},
    {n:"White Fox", u:"https://whitefoxboutique.com.au", t:["Y2K","辣妹"], c:"young"},
    {n:"Ongess", u:"https://www.ongess.com", t:["印花","度假"], c:"young"},
    {n:"Cider", u:"https://www.shopcider.com", t:["Z世代","甜酷"], c:"young"},
    {n:"Tata Dress", u:"https://www.tatadress.com", t:["牛仔","碎花"], c:"young"},
    {n:"Stylewe", u:"https://www.stylewe.com", t:["性感","礼服"], c:"young"},
    {n:"Bella Barnett", u:"https://www.bellabarnett.com", t:["夜店","亮片"], c:"young"},
    {n:"Garage", u:"https://www.garageclothing.com", t:["运动","卫衣"], c:"young"},
    {n:"Edikted", u:"https://edikted.com", t:["芭蕾core"], c:"young"},
    {n:"Odd Muse", u:"https://oddmuse.co.uk", t:["极简","轻奢"], c:"young"},
    {n:"Beginning Boutique", u:"https://www.beginningboutique.com", t:["澳洲","派对"], c:"young"},
    {n:"I.AM.GIA", u:"https://iamgia.com", t:["机能","废土"], c:"young"},
    {n:"Miaou", u:"https://miaou.com", t:["法式辣妹"], c:"young"},
    {n:"Lioness", u:"https://lionessfashion.com", t:["极简","冷淡"], c:"young"},
    {n:"Jaded London", u:"https://jadedldn.com", t:["街头","朋克"], c:"young"},
    {n:"Romwe", u:"https://us.romwe.com", t:["低价","暗黑"], c:"young"},
    {n:"Like My Choice", u:"https://likemychoice.com", t:["印花","波西米亚"], c:"young"},
    {n:"Shop Allison", u:"https://shopallison.com", t:["亮片","派对"], c:"young"},
    {n:"Mermaid Way", u:"https://mermaidway.com", t:["网纱","皮质"], c:"young"},
    {n:"Lulus", u:"https://www.lulus.com", t:["仙女裙"], c:"young"},
    {n:"Red Dress", u:"https://www.reddress.com", t:["名媛"], c:"young"},
    {n:"Retro Stage", u:"https://www.retro-stage.com", t:["复古","50s"], c:"young"},
    {n:"Choies", u:"https://www.choies.com", t:["爆品"], c:"young"},
    {n:"Emery Rose", u:"https://www.shopemeryrose.com", t:["印花","平价"], c:"young"},
    {n:"MOTF", u:"https://www.shopmotf.com", t:["少淑","通勤"], c:"young"},
    {n:"Glassons", u:"https://www.glassons.com", t:["澳新","休闲"], c:"young"},

    // Elegant
    {n:"Chicwish", u:"https://www.chicwish.com", t:["复古","甜美"], c:"elegant"},
    {n:"Coldwater Creek", u:"https://www.coldwatercreek.com", t:["成熟","自然"], c:"elegant"},
    {n:"Vici Collection", u:"https://www.vicicollection.com", t:["轻奢","通勤"], c:"elegant"},
    {n:"CutelyCovered", u:"https://cutelycovered.com", t:["教会","得体"], c:"elegant"},
    {n:"Da Barretta", u:"https://dabaretta.com", t:["中年","优雅"], c:"elegant"},
    {n:"Novodiva", u:"https://novodiva.com", t:["晚宴"], c:"elegant"},
    {n:"Dissh", u:"https://dissh.com", t:["极简","棉麻"], c:"elegant"},
    {n:"ASTR The Label", u:"https://www.astrthelabel.com", t:["西装","轻熟"], c:"elegant"},
    {n:"Abigails", u:"https://www.abigails.shop", t:["中东","长袍"], c:"elegant"},
    {n:"Rosie Dress", u:"https://www.rosiedress.com", t:["快时尚","通勤"], c:"elegant"},
    {n:"Her Fashioned Life", u:"https://www.shopltk.com/explore/herfashionedlife", t:["OldMoney"], c:"elegant"},
    {n:"LTK", u:"https://www.shopltk.com", t:["种草"], c:"elegant"},
    {n:"Free People", u:"https://www.freepeople.com", t:["波西米亚"], c:"elegant"},
    {n:"Oyrosy", u:"https://oyrosy.com", t:["西服"], c:"elegant"},
    {n:"Hot Lula", u:"https://www.hotlula.com", t:["连衣裙"], c:"elegant"},
    {n:"NA-KD", u:"https://www.na-kd.com", t:["北欧","通勤"], c:"elegant"},
    {n:"Uoozee", u:"https://www.uoozeefashion.com", t:["混合印花"], c:"elegant"},
    {n:"Tuckernuck", u:"https://tnuck.com", t:["贵妇","POLO"], c:"elegant"},
    {n:"Orolay", u:"https://www.orolay.com", t:["羽绒"], c:"elegant"},
    {n:"Ritaros", u:"https://www.ritaros.com/es", t:["西班牙","礼服"], c:"elegant"},
    {n:"Vivaia", u:"https://www.vivaia.com", t:["环保鞋"], c:"elegant"},

    // Sport
    {n:"Popilush", u:"https://www.popilush.com", t:["塑形"], c:"sport"},
    {n:"Oh Polly", u:"https://us.ohpolly.com", t:["瑜伽","紧身"], c:"sport"},
    {n:"OQQ", u:"https://oqq.com", t:["连体"], c:"sport"},
    {n:"PacSun", u:"https://www.pacsun.com", t:["滑板","潮牌"], c:"sport"},
    {n:"Aelfric Eden", u:"https://www.aelfriceden.com", t:["街头","oversize"], c:"sport"},
    {n:"Parthea", u:"https://www.azaleawang.com", t:["未来感"], c:"sport"},
    {n:"Dominnico", u:"https://dominnico.com", t:["秀场"], c:"sport"},
    {n:"Halara", u:"https://www.halara.com", t:["裙裤"], c:"sport"},

    // Curve
    {n:"Fashion Nova", u:"https://www.fashionnova.com", t:["大码辣妹"], c:"curve"},
    {n:"BloomChic", u:"https://www.bloomchic.com", t:["大码","通勤"], c:"curve"},
    {n:"LovelyWholesale", u:"https://lovelywholesale.com", t:["曲线","街景"], c:"curve"},
    {n:"Bellizimos", u:"https://www.bellizimos.com", t:["紧身","开叉"], c:"curve"},
    {n:"Forevershe", u:"https://www.forevershe.com", t:["修身","黑人"], c:"curve"},
    {n:"Dresspies", u:"https://www.dresspies.com", t:["礼服"], c:"curve"},
    {n:"Mourban", u:"https://www.mourban.com", t:["街拍"], c:"curve"},
    {n:"Missinlook", u:"https://www.missinlook.com", t:["派对"], c:"curve"},
    {n:"Knowfashionstyle", u:"https://www.knowfashionstyle.com", t:["印花"], c:"curve"},
    {n:"Wearvip", u:"https://wearvip.com", t:["夜店"], c:"curve"},
    {n:"Elevenurban", u:"https://elevenurban.com", t:["街头"], c:"curve"},
    {n:"Queenfy", u:"https://www.queenfy.com", t:["曲线"], c:"curve"},
    {n:"Outyfit", u:"https://outyfit.com", t:["基础"], c:"curve"},
    {n:"Newlydress", u:"https://www.newlydress.com", t:["修身"], c:"curve"},
    {n:"Pansygal", u:"https://www.pansygal.com", t:["休闲"], c:"curve"},
    {n:"Adoryme", u:"https://adoryme.com", t:["贴身"], c:"curve"},
    {n:"Curvedress", u:"https://curvedress.com", t:["大码"], c:"curve"},
    {n:"99jean", u:"https://99jean.com", t:["紧身"], c:"curve"},
    {n:"144mph", u:"https://www.144mph.com", t:["性感"], c:"curve"},
    {n:"Empress J", u:"https://empressjboutique.com", t:["女王"], c:"curve"},
    {n:"Rosyella", u:"https://www.rosyella.com", t:["曲线"], c:"curve"},
    {n:"Ezcute", u:"https://ezcute.com", t:["派对"], c:"curve"},

    // Fast
    {n:"NewChic", u:"https://www.newchic.com", t:["中老年","宽松"], c:"fast"},
    {n:"Zulily", u:"https://www.zulily.com", t:["家庭","折扣"], c:"fast"},
    {n:"FairySeason", u:"https://www.fairyseason.com", t:["平价","宽松"], c:"fast"},
    {n:"Lotd", u:"https://www.lotd.com", t:["快时尚"], c:"fast"},
    {n:"Missguided", u:"https://www.missguided.com", t:["派对"], c:"fast"},
    {n:"Linkshe", u:"https://www.linkshe.com", t:["节日","泳衣"], c:"fast"},
    {n:"Chicme", u:"https://www.chicme.com", t:["甜辣","街拍"], c:"fast"},
    {n:"Dresslily", u:"https://www.dresslily.com", t:["基础"], c:"fast"},
    {n:"Rotita", u:"https://www.rotita.com", t:["度假","小麦色"], c:"fast"},
    {n:"Liligal", u:"https://www.liligal.com", t:["基础"], c:"fast"},
    {n:"Molyca", u:"https://www.molyca.com", t:["纯色"], c:"fast"},
    {n:"Zaful", u:"https://www.zaful.com", t:["泳衣"], c:"fast"},
    {n:"Jollychic", u:"https://www.jollychic.com", t:["中东","长袖"], c:"fast"},
    {n:"Bootymust", u:"https://bootymust.com", t:["贴身"], c:"fast"},
    {n:"Forplay Catalog", u:"https://forplaycatalog.com", t:["情趣"], c:"fast"},
    {n:"Lingerie Diva", u:"https://lingeriediva.com", t:["内衣"], c:"fast"},
    {n:"Dresshead", u:"https://dresshead.com", t:["通勤"], c:"fast"},
    {n:"Suzhou Dress", u:"https://suzhoudress.com", t:["婚纱"], c:"fast"},
    {n:"Oshoplive", u:"https://www.oshoplive.com", t:["快时尚"], c:"fast"},
    {n:"Wanadress", u:"https://wanadress.com", t:["宴会"], c:"fast"},
    {n:"Ericdress", u:"https://www.ericdress.com", t:["婚礼"], c:"fast"},
    {n:"Polar Hearts", u:"https://www.polarhearts.com", t:["简约"], c:"fast"},
    {n:"Red Coco Star", u:"https://www.redcocostar.com", t:["修身"], c:"fast"},
    {n:"New Mina", u:"https://www.newmina.com", t:["基础"], c:"fast"},
    {n:"Mrcovic", u:"https://www.mrcovic.com", t:["A字裙"], c:"fast"},
    {n:"Follow Zap", u:"https://www.followzap.com", t:["快时尚"], c:"fast"},
    {n:"Adora Pretty", u:"https://www.adorapretty.com", t:["少女"], c:"fast"},
    {n:"Fabrus Online", u:"https://www.fabrusonline.com", t:["日常"], c:"fast"},
    {n:"Belle Wholesale", u:"https://www.bellewholesale.com", t:["印花"], c:"fast"},
    {n:"Ladifit", u:"https://www.ladifit.com", t:["修身"], c:"fast"},
    {n:"Divas Ruby", u:"https://www.divasruby.com", t:["名媛"], c:"fast"},
    {n:"Ninimour", u:"https://www.ninimour.com", t:["快时尚"], c:"fast"},
    {n:"Pick My Boutique", u:"https://www.pickmyboutique.com", t:["精选"], c:"fast"},
    {n:"Boutique Feel", u:"https://www.boutiquefeel.com", t:["紧身"], c:"fast"},
    {n:"TB Dress", u:"https://www.tbdress.com", t:["礼服"], c:"fast"},
    {n:"Cotton On", u:"https://www.cottonon.com", t:["平价"], c:"fast"},
    {n:"Reserved", u:"https://www.reserved.com", t:["东欧"], c:"fast"},

    // French
    {n:"PrettyLittleThing", u:"https://www.prettylittlething.us", t:["欧美辣妹"], c:"french"},
    {n:"Mango", u:"https://shop.mango.com", t:["简约"], c:"french"},
    {n:"SSENSE", u:"https://www.ssense.com", t:["设计师"], c:"french"},
    {n:"Virgo Boutique", u:"https://virgo-boutique.com", t:["优雅"], c:"french"},
    {n:"Caroll", u:"https://www.caroll.com", t:["职场"], c:"french"},
    {n:"Claudie Pierlot", u:"https://www.claudiepierlot.com", t:["轻奢"], c:"french"},
    {n:"Balzac Paris", u:"https://www.balzac-paris.fr", t:["优雅"], c:"french"},
    {n:"Marie Marot", u:"https://www.mariemarot.com", t:["白衬衫"], c:"french"},
    {n:"Boutique Keva", u:"https://www.boutiquekeva.com/en/", t:["成熟"], c:"french"},
    {n:"Intemporel", u:"https://www.intemporel.shop/", t:["极简"], c:"french"},
    {n:"Prettywire", u:"https://www.prettywire.fr", t:["森系"], c:"french"},
    {n:"Promod", u:"https://www.promod.com/en/", t:["平价"], c:"french"},
    {n:"Petite Mendigote", u:"https://www.petitemendigote.com", t:["文艺"], c:"french"},
    {n:"Hello Moon", u:"https://www.hellomoon-shop.com/fr", t:["简约"], c:"french"},
    {n:"Minodusud", u:"https://www.minodusud.com/fr/pret-a-porter", t:["波西"], c:"french"},

    // Euro
    {n:"Shopaholics Dream", u:"https://shopaholicsdream.pl", t:["快时尚"], c:"euro"},
    {n:"Andzela", u:"https://www.andzela.com", t:["平价"], c:"euro"},
    {n:"Milutka", u:"https://www.milutka.com", t:["立陶宛"], c:"euro"},
    {n:"Nasha Moda", u:"https://www.nashamoda.by", t:["白俄罗斯"], c:"euro"},
    {n:"Blyzka", u:"https://blyzka.by", t:["通勤"], c:"euro"},
    {n:"Knitteriet", u:"https://knitteriet.no", t:["挪威"], c:"euro"},
    {n:"Pachamama", u:"https://www.pachamamaknitwear.com/Womens-Cardigans", t:["英国"], c:"euro"},
    {n:"Rebellious", u:"https://www.rebelliousfashion.co.uk", t:["英国"], c:"euro"},
    {n:"Qbunitastore", u:"https://www.qbunitastore.com.br", t:["巴西"], c:"euro"},
    {n:"Magmac", u:"https://www.magmac.pl", t:["波兰"], c:"euro"},
    {n:"So Italian", u:"https://www.soitalian.pl/pl", t:["意式"], c:"euro"},
    {n:"La Butik", u:"https://www.labutik.sklep.pl", t:["波兰"], c:"euro"},
    {n:"Elagia", u:"https://www.elagia.com", t:["西装"], c:"euro"},

    // Gown
    {n:"Meshki", u:"https://www.meshki.com.au", t:["修身"], c:"gown"},
    {n:"Missord", u:"https://www.missord.com", t:["礼服"], c:"gown"},
    {n:"Faeriesty", u:"https://faeriesty.com", t:["派对"], c:"gown"},
    {n:"Zimmermann", u:"https://www.zimmermann.com", t:["高奢"], c:"gown"},
    {n:"Dries Van Noten", u:"https://www.driesvannoten.com", t:["艺术"], c:"gown"},
    {n:"Blumarine", u:"https://www.blumarine.com", t:["高定"], c:"gown"},
    {n:"Anna Sui", u:"https://annasui.com", t:["复古"], c:"gown"},
    {n:"Philosophy", u:"https://www.philosophyofficial.com", t:["名媛"], c:"gown"},
    {n:"Poster Girl", u:"https://poster-girl.com", t:["漆皮"], c:"gown"},
    {n:"Femkit", u:"https://femkit.de", t:["宫廷"], c:"gown"},
    {n:"Somnia Romantica", u:"https://somniaromantica.com", t:["哥特"], c:"gown"},
    {n:"Linennaive", u:"https://www.linennaive.com", t:["亚麻"], c:"gown"},
    {n:"Jean Paul Gaultier", u:"https://fashion.jeanpaulgaultier.com", t:["解构"], c:"gown"},
    {n:"Ever-Pretty", u:"https://www.ever-pretty.com", t:["平价"], c:"gown"},
    {n:"Global Lover", u:"https://global-lover.com", t:["度假"], c:"gown"},

    // Denim
    {n:"AngelHeart", u:"https://angelheartboutique.com/", t:["西部"], c:"denim"},
    {n:"Urban Outfitters", u:"https://www.urbanoutfitters.com", t:["工装"], c:"denim"},
    {n:"Ronner Design", u:"https://ronnerdesign.com", t:["骑马"], c:"denim"},
    {n:"Monster Valley", u:"https://www.monstervalley.com", t:["户外"], c:"denim"},

    // Linen
    {n:"Airily", u:"https://airily.eu/en/", t:["欧洲"], c:"linen"},
    {n:"Soolinen", u:"https://soolinen.com", t:["文艺"], c:"linen"},
    {n:"Fantasy Linen", u:"https://www.fantasylinen.com", t:["手工"], c:"linen"},
    {n:"VeryBuy", u:"https://m.verybuy.cc", t:["台系"], c:"linen"},
    {n:"Big Save", u:"https://www.bigsave.com.tw", t:["家居"], c:"linen"},
    {n:"Minne", u:"https://minne.com", t:["手作"], c:"linen"},
    {n:"Mattecoco", u:"https://www.mattecoco.com", t:["小麦色"], c:"linen"},
    {n:"Hippie Chic", u:"https://hippiechicshop.com", t:["波西"], c:"linen"}
];